/**
 * QA Test 1 — OTP invalid-attempt cap (max 5, then LOCKED).
 *
 * Proves with REAL parallel PostgreSQL transactions that:
 *   - 20 concurrent invalid OTP submissions against the SAME OTP row
 *     result in EXACTLY 5 successful attempts increments,
 *     and the remaining 15 are rejected (NOT_FOUND_OR_EXPIRED).
 *   - After all 20 complete, the OTP row has attempts === maxAttempts (5)
 *     — i.e. the challenge is LOCKED.
 *   - A subsequent valid code submission is rejected (LOCKED).
 *
 * The test calls `consumeOtp()` directly from `src/lib/otp.ts` — the
 * SAME function the HTTP routes call. The transaction semantics are
 * identical to what production will experience.
 *
 * The OTP code is generated by `issueOtp()` and the raw code is captured
 * BEFORE the test starts. The test then submits 20 WRONG codes (raw code
 * + 1 modulo 10) in parallel — all invalid.
 */

import { PrismaClient } from '@prisma/client'
import { issueOtp, consumeOtp, hashOtpCode, type OtpPurpose } from '../src/lib/otp'

const prisma = new PrismaClient()

async function main() {
  console.log('=== QA Test 1: OTP invalid-attempt cap (max 5) ===')

  const user = await prisma.user.findUnique({
    where: { email: 'qa-v2-verify@example.com' },
    select: { id: true },
  })
  if (!user) throw new Error('QA user qa-v2-verify@example.com not found — run seed-qa first')

  // Clean up any prior OTP rows for this user (idempotent re-run).
  await prisma.otpCode.deleteMany({ where: { userId: user.id } })

  // Issue one fresh OTP. The raw `code` is captured for later sanity-check
  // (we want to verify that after lockout, even the CORRECT code is rejected).
  const issueOutcome = await issueOtp({
    userId: user.id,
    purpose: 'EMAIL_VERIFICATION',
  })
  if (issueOutcome.result !== 'ISSUED') {
    throw new Error(
      `Setup issueOtp returned ${issueOutcome.result} — expected ISSUED for fresh user. ` +
        'Is the QA DB clean? Run seed-qa first.'
    )
  }
  const correctCode = issueOutcome.code
  console.log(`[setup] Issued OTP for ${user.id}. Raw code captured (NOT displayed in prod logs).`)

  // Sanity: verify the HMAC round-trips — correctCode should consume OK on first try
  // in a SEPARATE test below. Here we'll only submit WRONG codes.

  // Construct a guaranteed-wrong code: increment the last digit modulo 10.
  // This guarantees the code is well-formed (6-digit) but never equals the
  // actual code (because we modify the last digit).
  const wrongCode = (parseInt(correctCode, 10) + 1).toString().padStart(6, '0').slice(-6)
  if (wrongCode === correctCode) {
    // Astronomically unlikely (1 in 10), but defensive
    throw new Error('wrongCode collided with correctCode — rerun')
  }
  console.log(`[setup] Wrong code constructed (last digit incremented mod 10).`)

  // Fire 20 parallel invalid submissions
  const N = 20
  console.log(`[test] Firing ${N} parallel invalid submissions...`)
  const t0 = Date.now()
  const results = await Promise.all(
    Array.from({ length: N }, (_, i) =>
      consumeOtp({
        userId: user.id,
        purpose: 'EMAIL_VERIFICATION' as OtpPurpose,
        code: wrongCode,
      })
        .then((r) => ({ idx: i, result: r }))
        .catch((e) => ({ idx: i, error: String(e) }))
    )
  )
  const elapsed = Date.now() - t0
  console.log(`[test] All ${N} parallel calls returned in ${elapsed}ms`)

  // Tally results
  const tally: Record<string, number> = {}
  for (const r of results) {
    const key = 'result' in r ? r.result.result : 'THREW'
    tally[key] = (tally[key] ?? 0) + 1
  }
  console.log('[test] Tally of results:')
  for (const [k, v] of Object.entries(tally)) {
    console.log(`        ${k.padEnd(24)} = ${v}`)
  }

  // Read the final OTP state from the DB
  const finalOtp = await prisma.otpCode.findFirst({
    where: { userId: user.id, purpose: 'EMAIL_VERIFICATION' },
    orderBy: { createdAt: 'desc' },
    select: { id: true, attempts: true, maxAttempts: true, consumedAt: true },
  })
  console.log('[verify] Final OTP row state:', finalOtp)

  // Assertions
  const wrongCount = tally['WRONG_CODE'] ?? 0
  const notFoundCount = tally['NOT_FOUND_OR_EXPIRED'] ?? 0
  const okCount = tally['OK'] ?? 0
  const alreadyCount = tally['ALREADY_CONSUMED'] ?? 0

  const pass =
    okCount === 0 &&
    alreadyCount === 0 &&
    wrongCount === 5 &&
    notFoundCount === 15 &&
    finalOtp !== null &&
    finalOtp.attempts === finalOtp.maxAttempts &&
    finalOtp.consumedAt === null

  console.log('\n--- ASSERTIONS ---')
  console.log(`OK count            = ${okCount}        (expected 0)             ${okCount === 0 ? 'PASS' : 'FAIL'}`)
  console.log(`ALREADY_CONSUMED    = ${alreadyCount}        (expected 0)             ${alreadyCount === 0 ? 'PASS' : 'FAIL'}`)
  console.log(`WRONG_CODE          = ${wrongCount}       (expected 5)             ${wrongCount === 5 ? 'PASS' : 'FAIL'}`)
  console.log(`NOT_FOUND_OR_EXPIRED= ${notFoundCount}      (expected 15)            ${notFoundCount === 15 ? 'PASS' : 'FAIL'}`)
  console.log(`attempts == maxAttempts = ${finalOtp?.attempts === finalOtp?.maxAttempts} (attempts=${finalOtp?.attempts}, max=${finalOtp?.maxAttempts})`)
  console.log(`consumedAt IS NULL      = ${finalOtp?.consumedAt === null}`)
  console.log(`\nOVERALL: ${pass ? 'PASS ✅' : 'FAIL ❌'}`)

  // ---- Bonus assertion: even the CORRECT code is now rejected (LOCKED) ----
  console.log('\n--- BONUS: correct code after lockout is rejected ---')
  const correctAfterLock = await consumeOtp({
    userId: user.id,
    purpose: 'EMAIL_VERIFICATION',
    code: correctCode,
  })
  console.log(`consumeOtp(correctCode) = ${correctAfterLock.result}`)
  const bonusPass = correctAfterLock.result === 'NOT_FOUND_OR_EXPIRED'
  console.log(`OVERALL (bonus): ${bonusPass ? 'PASS ✅' : 'FAIL ❌'}`)

  if (!pass || !bonusPass) process.exit(1)
}

main()
  .catch((e) => {
    console.error('QA Test 1 FAILED:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
